[tool.poetry]
name = "running-for-stats"
version = "0.1.0"
description = ""
authors = ["Willem Houck"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
